modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="permnodes"
version="1.0.1"
displayName="PermNodes"
description='''
Permission-based restrictions for block placement/mining and crafting.
Optionally integrates with LuckPerms and uses a namespace:path scheme.
'''

[[dependencies.permnodes]]
modId = "neoforge"
type = "required"
versionRange = "[21.8.46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.permnodes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.permnodes]]
modId="luckperms"
type="optional"
versionRange="[5,)"
ordering="NONE"
side="SERVER"

